apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express
  labels:
    apps: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: mongo-express
  template:
    metadata:
      labels:
        apps: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        ports:
        - containerPort: 8081     
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: ME_CONFIG_MONGODB_SERVER
          configMapKeyRef:
            name: mongodb-config
            key: database_url
---